language: node_js
node_js:
  - "8"
  - "10"
  - "12"

script: $TEST_COMMAND

env:
  global:
    - USE_SAUCE=true
    - TEST_COMMAND="bash travis-core-script.sh"
    - secure: WSPWhlnC4mWSnSPquX+m1/BCu5ch5NygkaHuM2Nea7lD8oS3XLX8QncZZAsQ4lnNfqoDDuBOizG0AESiqNvE4y6x5qvLLTS6q+ce255ZEMZ71TBdZgDEEvGMEjOPPsVXiXyTQOP1lwOPlrbZvaPgWV7e11KIBab6DfFcQpnvDgo=
    - secure: SW7CJhZnwaNT749Gdnhvqb5rbXlAOsygUAzh9qhtyvbqXKkmJdBIEsO01YF6pbju1X2twE9JvWCOxeZju43NgQChJlPsGbjY2j3k/TdQeTAJesQe2K7ytwghunI30gjEovtRH0T3w1EmcKPH8yj5eBIcB2OYoJHx8KEC7e68q1g=
  matrix:
    - TEST_COMMAND="npm test"


matrix:
  include:
    - env: JASMINE_BROWSER="phantomjs" USE_SAUCE=false
    - env: JASMINE_BROWSER="firefox" SAUCE_BROWSER_VERSION='' SAUCE_OS="Linux"
      if: type != pull_request
      addons:
        sauce_connect: true
    - env: JASMINE_BROWSER="chrome" SAUCE_BROWSER_VERSION='' SAUCE_OS="Linux"
      if: type != pull_request
      addons:
        sauce_connect: true
    - env: JASMINE_BROWSER="safari" SAUCE_BROWSER_VERSION="10" SAUCE_OS="OS X 10.12"
      if: type != pull_request
      addons:
        sauce_connect: true
    - env: JASMINE_BROWSER="safari" SAUCE_BROWSER_VERSION="9" SAUCE_OS="OS X 10.11"
      if: type != pull_request
      addons:
        sauce_connect: true
    - env: JASMINE_BROWSER="safari" SAUCE_BROWSER_VERSION="8" SAUCE_OS="OS X 10.10"
      if: type != pull_request
      addons:
        sauce_connect: true
    - env: JASMINE_BROWSER="MicrosoftEdge" SAUCE_BROWSER_VERSION="15" SAUCE_OS="Windows 10"
      if: type != pull_request
      addons:
        sauce_connect: true
    - env: JASMINE_BROWSER="internet explorer" SAUCE_BROWSER_VERSION=11 SAUCE_OS="Windows 8.1"
      if: type != pull_request
      addons:
        sauce_connect: true
    - env: JASMINE_BROWSER="internet explorer" SAUCE_BROWSER_VERSION=10 SAUCE_OS="Windows 8"
      if: type != pull_request
      addons:
        sauce_connect: true
